"""create station table

Revision ID: 67dd7447cf46
Revises: 
Create Date: 2026-09-20 22:33:10.036523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67dd7447cf46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('place_type', sa.String(length=50), nullable=True),
    sa.Column('owner_unit', sa.String(length=200), nullable=True),
    sa.Column('install_spot', sa.String(length=300), nullable=True),
    sa.Column('open_hours', sa.String(length=100), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('maintainer', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sampled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coliform', sa.String(length=30), nullable=True),
    sa.Column('quality_url', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.create_index('idx_station_latlon', ['lat', 'lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_station_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_status'))
        batch_op.drop_index(batch_op.f('ix_station_external_id'))
        batch_op.drop_index(batch_op.f('ix_station_district'))
        batch_op.drop_index(batch_op.f('ix_station_city'))
        batch_op.drop_index('idx_station_latlon')

    op.drop_table('station')
    # ### end Alembic commands ###
