"""create report table

Revision ID: 3556b758354d
Revises: 67dd7447cf46
Create Date: 2026-09-20 22:46:05.555945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3556b758354d'
down_revision: Union[str, Sequence[str], None] = '67dd7447cf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BROKEN', 'NO_WATER', 'DIRTY', 'GOOD', 'OTHER', name='reporttype', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_station_id'))
        batch_op.drop_index(batch_op.f('ix_report_created_at'))

    op.drop_table('report')
    # ### end Alembic commands ###
